### TRANSFORM SINGLE LABEL DATASET TO MULTI-LABEL DATASET

#### PART 1: Transform the Single Label Dialect CSV into a format accepting multiple dialects

After Data preprocessing only change the path of train_dataset, and run the code normally.

In [14]:
import pandas as pd

train_path_1 = "../NADI2024_subtask1/subtask1/train/NADI2020-TWT.tsv"
train_path_2 = "../NADI2024_subtask1/subtask1/train/NADI2021-TWT.tsv"
train_path_3 = "../NADI2024_subtask1/subtask1/train/NADI2023-TWT.tsv"

train_1 = pd.read_csv(train_path_1, sep='\t')
train_2 = pd.read_csv(train_path_2, sep='\t')
train_3 = pd.read_csv(train_path_3, sep='\t')

train_dataset = pd.concat([train_1, train_2, train_3], ignore_index=True)
train_dataset.to_csv("../NADI2024_subtask1/subtask1/train/CONCAT.tsv", index=False)

In [15]:
train_dataset.columns

Index(['#1_id', '#2_content', '#3_label', '#4_province_label'], dtype='object')

In [34]:
train_dataset.rename(columns={'#2_content': 'tweet', '#3_label': 'label', '#1_id':'id'}, inplace=True)

In [35]:
train_dataset.drop(columns=['#4_province_label'], inplace=True)

In [36]:
train_dataset.columns

Index(['id', 'tweet', 'label'], dtype='object')

In [37]:
train_dataset['label'].unique()

array(['Iraq', 'Egypt', 'Morocco', 'Libya', 'UAE', 'Saudi_Arabia',
       'Bahrain', 'Syria', 'Lebanon', 'Oman', 'Palestine', 'Algeria',
       'Jordan', 'Tunisia', 'Kuwait', 'Yemen', 'Sudan', 'Qatar'],
      dtype=object)

In [38]:
countries = ['Iraq', 'Egypt', 'Morocco', 'Libya', 'UAE', 'Saudi_Arabia',
             'Bahrain', 'Syria', 'Lebanon', 'Oman', 'Palestine', 'Algeria',
             'Jordan', 'Tunisia', 'Kuwait', 'Yemen', 'Sudan', 'Qatar']

In [39]:
# Creating a new column for every country and make it one hot encoded
df_one_hot = pd.get_dummies(train_dataset['label'], prefix='', prefix_sep='').astype(int)

In [40]:
df_one_hot

,Algeria,Bahrain,Egypt,Iraq,Jordan,Kuwait,Lebanon,Libya,Morocco,Oman,Palestine,Qatar,Saudi_Arabia,Sudan,Syria,Tunisia,UAE,Yemen
0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58763,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
58764,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
58765,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
58766,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
58767,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [41]:
df_final = pd.concat([train_dataset.drop('label', axis=1), df_one_hot], axis=1)

In [42]:
df_final

,id,tweet,Algeria,Bahrain,Egypt,Iraq,Jordan,Kuwait,Lebanon,Libya,Morocco,Oman,Palestine,Qatar,Saudi_Arabia,Sudan,Syria,Tunisia,UAE,Yemen
0,TRAIN_1,الفار العور يشوف فقط كيسي ومايشوف ماتويد,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,TRAIN_2,ي دينيييي ربنا يستر,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,TRAIN_3,أساساً نسبكم قذر ونجس بلاش تتفاخروا بنجاستكم ي...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,TRAIN_4,ليْسَت كُل المَشَاعِرِ تَحْتَاجُ إلى حَبِيب بَ...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,TRAIN_5,لأ ني حاضرها هذي لايف,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58763,subtask1_train_17996,USER شكد سفله تثمين الخطوات اولاد وين الخدمات ...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
58764,subtask1_train_17997,USER القايد صالح راهو يلهي فيك فالعلم والهويه ...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
58765,subtask1_train_17998,وهسه وينك كالو باخر الدنيا حلم باجر تشوفه جيت ...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
58766,subtask1_train_17999,وهو العيد يبقي عيد برده من غير البحر,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
58767,subtask1_train_18000,منو الحيوان الي قاعد يستعرض هالحزه شجوك ي تبن,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [43]:
df_final.to_csv("../NADI2024_subtask1/subtask1/train/CONCAT_ONE_HOT.tsv", index=False)

### PART 2: Get the dataset with multi-label setting and fill it using prompt engineering GPT 4

After preprocessing, run the following the same as before afetr changing the above cells.

In [47]:
df = pd.read_csv("../NADI2024_subtask1/subtask1/train/CONCAT_ONE_HOT.tsv")

In [50]:
# Column to prevent from sending the prompt twice
if 'Computed' not in df.columns:
    df['Computed'] = 'no'

df.to_csv("../NADI2024_subtask1/subtask1/train/CONCAT_MULTI_LABEL.csv", index=False)
path = "../NADI2024_subtask1/subtask1/train/CONCAT_MULTI_LABEL.csv"

In [56]:
from dotenv import load_dotenv
import json
import os
from openai import OpenAI

load_dotenv()

True

In [57]:
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

In [82]:
def get_dialect_classification(tweet):
    prompt = f"""You are a native Arabic Speaker and Linguist with a vast knowledge of Arabic dialectal constituents. We have a sentence and we want to know if it's possibly within one of the following dialects: 'Iraq, Egypt, Morocco, Libya, UAE, Saudi_Arabia, Bahrain, Syria, Lebanon, Oman, Palestine, Algeria, Jordan, Tunisia, Kuwait, Yemen, Sudan, Qatar'. 

Run the prompt independently for every dialect of the listed above and return a JSON object with 0 or 1 for every dialect. Return nothing else but the JSON object.

Input sentence: {tweet}"""

    try:
        stream = client.chat.completions.create(
            model="gpt-4",  
            messages=[
                {"role": "system", "content": "You are a native Arabic speaker and dialect expert."},
                {"role": "user", "content": prompt}
            ],
            stream=True  
        )

        result_content = ""
        for chunk in stream:
            content = getattr(chunk.choices[0].delta, 'content', None)
            if content is not None:
                result_content += content
        
        # it differs from gpt-4o and gpt4 so make sure to print first and check
        result = json.loads(result_content)
        return result

    except Exception as e:
        print(f"Error processing tweet: {tweet}. Error: {e}")
        return None

In [83]:
get_dialect_classification("السلام عليكم")

{'Iraq': 1,
 'Egypt': 1,
 'Morocco': 1,
 'Libya': 1,
 'UAE': 1,
 'Saudi_Arabia': 1,
 'Bahrain': 1,
 'Syria': 1,
 'Lebanon': 1,
 'Oman': 1,
 'Palestine': 1,
 'Algeria': 1,
 'Jordan': 1,
 'Tunisia': 1,
 'Kuwait': 1,
 'Yemen': 1,
 'Sudan': 1,
 'Qatar': 1}

In [96]:
import pandas as pd

def process_tweets_in_batches(path, batch_size, save_threshold):
    
    chunk_size = batch_size
    rows_processed = 0
    processed = 0

    for chunk in pd.read_csv(path, chunksize=chunk_size):
        rows_to_update = []
        for idx, row in chunk.iterrows():
            if row['Computed'] == 'no':  # Process only if not already computed
                result = get_dialect_classification(row['tweet'])
                print("Processed tweet: ", row['tweet'])
                processed += 1
                if result: 
                    for country in countries:
                        chunk.at[idx, country] = result.get(country, 0)
                    chunk.at[idx, 'Computed'] = 'yes'
                    rows_to_update.append(row['id'])

        if len(rows_to_update) >= save_threshold:
            df_original = pd.read_csv(path)  
            df_original.update(chunk[chunk['id'].isin(rows_to_update)])  
            df_original.to_csv(path, index=False) 
            rows_processed += len(rows_to_update)
            print(f"Saved after processing {rows_processed} updated rows.")
        
        rows_to_update = []
        if processed >= 10:
            break

        # experimental purposes
        if len(rows_to_update) > 0:
            print(f"Processed {len(rows_to_update)} rows.")
    
    print("All batches processed.")

process_tweets_in_batches(path, 10, 10)

Processed tweet:  #باقي_يومين_وتدفي_جيبك ونا بعد ابي مثلكم ادفي يديني اءء اءءpic.twitter.com/YQp64JJADh
Processed tweet:  بكفي فلسفة هبلة
Processed tweet:  واش رايكم خاوتي فالموهبة تاعي فالرسم pic.twitter.com/tAbdNgkkrg
Processed tweet:  انكسار هذه الفترة ثقيل جدًا - خارت قواي -
Processed tweet:  عمرها ما هتوحشني .. الحاجه الوحيده الي كانت حلوه في السنه إني عرفت ناس ومدرسين حلوين بس كدة ..https://twitter.com/ahmedlight9/status/1126489885483905024 …
Processed tweet:  يالي حاطه راس ابوكي ف الطين
Processed tweet:  اللَّهُمَّ طهر قلبي من النفاق ، وعملي من الرياء ، ولساني من الكذب ، وعيني من الخيانة http://du3a.org
Processed tweet:  على قد ما العهد مفلّس وموجوع من ضغط الثورة، انجبر سليم جريصاتي يستقبل بقصر بعبدا وفد من الشباب الناجحين المتقدمين لمجلس الخدمة المدنية وأغدق عليهم الوعود وانو نحنا بأمركم وتكرم عينكم !
Processed tweet:  عبالي تبقى للدوم وابد ماتبتعديوم
Processed tweet:  صحتين وهنا بس من أين لك هذا أكيد انت عميل السفارة
Saved after processing 10 updated rows.
All batches processed.